/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ServicesSidewalkRouteImport } from './routes/services/sidewalk'
import { Route as ServicesResidentialRouteImport } from './routes/services/residential'
import { Route as ServicesRemodelingRouteImport } from './routes/services/remodeling'
import { Route as ServicesPatiosRouteImport } from './routes/services/patios'
import { Route as ServicesInteriorExteriorRouteImport } from './routes/services/interior-exterior'
import { Route as ServicesHomeImprovementsRouteImport } from './routes/services/home-improvements'
import { Route as ServicesHomeAdditionsRouteImport } from './routes/services/home-additions'
import { Route as ServicesFoundationRouteImport } from './routes/services/foundation'
import { Route as ServicesFencingRouteImport } from './routes/services/fencing'
import { Route as ServicesDrivewayRouteImport } from './routes/services/driveway'
import { Route as ServicesDecksRouteImport } from './routes/services/decks'
import { Route as ServicesCommercialRouteImport } from './routes/services/commercial'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSidewalkRoute = ServicesSidewalkRouteImport.update({
  id: '/sidewalk',
  path: '/sidewalk',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesResidentialRoute = ServicesResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRemodelingRoute = ServicesRemodelingRouteImport.update({
  id: '/remodeling',
  path: '/remodeling',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPatiosRoute = ServicesPatiosRouteImport.update({
  id: '/patios',
  path: '/patios',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInteriorExteriorRoute =
  ServicesInteriorExteriorRouteImport.update({
    id: '/interior-exterior',
    path: '/interior-exterior',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHomeImprovementsRoute =
  ServicesHomeImprovementsRouteImport.update({
    id: '/home-improvements',
    path: '/home-improvements',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHomeAdditionsRoute = ServicesHomeAdditionsRouteImport.update({
  id: '/home-additions',
  path: '/home-additions',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFoundationRoute = ServicesFoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFencingRoute = ServicesFencingRouteImport.update({
  id: '/fencing',
  path: '/fencing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDrivewayRoute = ServicesDrivewayRouteImport.update({
  id: '/driveway',
  path: '/driveway',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDecksRoute = ServicesDecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCommercialRoute = ServicesCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/decks': typeof ServicesDecksRoute
  '/services/driveway': typeof ServicesDrivewayRoute
  '/services/fencing': typeof ServicesFencingRoute
  '/services/foundation': typeof ServicesFoundationRoute
  '/services/home-additions': typeof ServicesHomeAdditionsRoute
  '/services/home-improvements': typeof ServicesHomeImprovementsRoute
  '/services/interior-exterior': typeof ServicesInteriorExteriorRoute
  '/services/patios': typeof ServicesPatiosRoute
  '/services/remodeling': typeof ServicesRemodelingRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/sidewalk': typeof ServicesSidewalkRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/decks': typeof ServicesDecksRoute
  '/services/driveway': typeof ServicesDrivewayRoute
  '/services/fencing': typeof ServicesFencingRoute
  '/services/foundation': typeof ServicesFoundationRoute
  '/services/home-additions': typeof ServicesHomeAdditionsRoute
  '/services/home-improvements': typeof ServicesHomeImprovementsRoute
  '/services/interior-exterior': typeof ServicesInteriorExteriorRoute
  '/services/patios': typeof ServicesPatiosRoute
  '/services/remodeling': typeof ServicesRemodelingRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/sidewalk': typeof ServicesSidewalkRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/decks': typeof ServicesDecksRoute
  '/services/driveway': typeof ServicesDrivewayRoute
  '/services/fencing': typeof ServicesFencingRoute
  '/services/foundation': typeof ServicesFoundationRoute
  '/services/home-additions': typeof ServicesHomeAdditionsRoute
  '/services/home-improvements': typeof ServicesHomeImprovementsRoute
  '/services/interior-exterior': typeof ServicesInteriorExteriorRoute
  '/services/patios': typeof ServicesPatiosRoute
  '/services/remodeling': typeof ServicesRemodelingRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/sidewalk': typeof ServicesSidewalkRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/commercial'
    | '/services/decks'
    | '/services/driveway'
    | '/services/fencing'
    | '/services/foundation'
    | '/services/home-additions'
    | '/services/home-improvements'
    | '/services/interior-exterior'
    | '/services/patios'
    | '/services/remodeling'
    | '/services/residential'
    | '/services/sidewalk'
    | '/dashboard/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/reviews'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/commercial'
    | '/services/decks'
    | '/services/driveway'
    | '/services/fencing'
    | '/services/foundation'
    | '/services/home-additions'
    | '/services/home-improvements'
    | '/services/interior-exterior'
    | '/services/patios'
    | '/services/remodeling'
    | '/services/residential'
    | '/services/sidewalk'
    | '/dashboard'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/commercial'
    | '/services/decks'
    | '/services/driveway'
    | '/services/fencing'
    | '/services/foundation'
    | '/services/home-additions'
    | '/services/home-improvements'
    | '/services/interior-exterior'
    | '/services/patios'
    | '/services/remodeling'
    | '/services/residential'
    | '/services/sidewalk'
    | '/dashboard/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sidewalk': {
      id: '/services/sidewalk'
      path: '/sidewalk'
      fullPath: '/services/sidewalk'
      preLoaderRoute: typeof ServicesSidewalkRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/residential': {
      id: '/services/residential'
      path: '/residential'
      fullPath: '/services/residential'
      preLoaderRoute: typeof ServicesResidentialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/remodeling': {
      id: '/services/remodeling'
      path: '/remodeling'
      fullPath: '/services/remodeling'
      preLoaderRoute: typeof ServicesRemodelingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/patios': {
      id: '/services/patios'
      path: '/patios'
      fullPath: '/services/patios'
      preLoaderRoute: typeof ServicesPatiosRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/interior-exterior': {
      id: '/services/interior-exterior'
      path: '/interior-exterior'
      fullPath: '/services/interior-exterior'
      preLoaderRoute: typeof ServicesInteriorExteriorRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/home-improvements': {
      id: '/services/home-improvements'
      path: '/home-improvements'
      fullPath: '/services/home-improvements'
      preLoaderRoute: typeof ServicesHomeImprovementsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/home-additions': {
      id: '/services/home-additions'
      path: '/home-additions'
      fullPath: '/services/home-additions'
      preLoaderRoute: typeof ServicesHomeAdditionsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/foundation': {
      id: '/services/foundation'
      path: '/foundation'
      fullPath: '/services/foundation'
      preLoaderRoute: typeof ServicesFoundationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/fencing': {
      id: '/services/fencing'
      path: '/fencing'
      fullPath: '/services/fencing'
      preLoaderRoute: typeof ServicesFencingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/driveway': {
      id: '/services/driveway'
      path: '/driveway'
      fullPath: '/services/driveway'
      preLoaderRoute: typeof ServicesDrivewayRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/decks': {
      id: '/services/decks'
      path: '/decks'
      fullPath: '/services/decks'
      preLoaderRoute: typeof ServicesDecksRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/commercial': {
      id: '/services/commercial'
      path: '/commercial'
      fullPath: '/services/commercial'
      preLoaderRoute: typeof ServicesCommercialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesCommercialRoute: typeof ServicesCommercialRoute
  ServicesDecksRoute: typeof ServicesDecksRoute
  ServicesDrivewayRoute: typeof ServicesDrivewayRoute
  ServicesFencingRoute: typeof ServicesFencingRoute
  ServicesFoundationRoute: typeof ServicesFoundationRoute
  ServicesHomeAdditionsRoute: typeof ServicesHomeAdditionsRoute
  ServicesHomeImprovementsRoute: typeof ServicesHomeImprovementsRoute
  ServicesInteriorExteriorRoute: typeof ServicesInteriorExteriorRoute
  ServicesPatiosRoute: typeof ServicesPatiosRoute
  ServicesRemodelingRoute: typeof ServicesRemodelingRoute
  ServicesResidentialRoute: typeof ServicesResidentialRoute
  ServicesSidewalkRoute: typeof ServicesSidewalkRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCommercialRoute: ServicesCommercialRoute,
  ServicesDecksRoute: ServicesDecksRoute,
  ServicesDrivewayRoute: ServicesDrivewayRoute,
  ServicesFencingRoute: ServicesFencingRoute,
  ServicesFoundationRoute: ServicesFoundationRoute,
  ServicesHomeAdditionsRoute: ServicesHomeAdditionsRoute,
  ServicesHomeImprovementsRoute: ServicesHomeImprovementsRoute,
  ServicesInteriorExteriorRoute: ServicesInteriorExteriorRoute,
  ServicesPatiosRoute: ServicesPatiosRoute,
  ServicesRemodelingRoute: ServicesRemodelingRoute,
  ServicesResidentialRoute: ServicesResidentialRoute,
  ServicesSidewalkRoute: ServicesSidewalkRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
