/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesWiringRewiringRouteImport } from './routes/services/wiring-rewiring'
import { Route as ServicesSecuritySystemsRouteImport } from './routes/services/security-systems'
import { Route as ServicesResidentialRouteImport } from './routes/services/residential'
import { Route as ServicesPanelUpgradesRouteImport } from './routes/services/panel-upgrades'
import { Route as ServicesIndustrialRouteImport } from './routes/services/industrial'
import { Route as ServicesGeneratorRouteImport } from './routes/services/generator'
import { Route as ServicesEvChargerRouteImport } from './routes/services/ev-charger'
import { Route as ServicesEmergencyRouteImport } from './routes/services/emergency'
import { Route as ServicesCommercialRouteImport } from './routes/services/commercial'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWiringRewiringRoute = ServicesWiringRewiringRouteImport.update({
  id: '/wiring-rewiring',
  path: '/wiring-rewiring',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSecuritySystemsRoute = ServicesSecuritySystemsRouteImport.update({
  id: '/security-systems',
  path: '/security-systems',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesResidentialRoute = ServicesResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPanelUpgradesRoute = ServicesPanelUpgradesRouteImport.update({
  id: '/panel-upgrades',
  path: '/panel-upgrades',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesIndustrialRoute = ServicesIndustrialRouteImport.update({
  id: '/industrial',
  path: '/industrial',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGeneratorRoute = ServicesGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEvChargerRoute = ServicesEvChargerRouteImport.update({
  id: '/ev-charger',
  path: '/ev-charger',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEmergencyRoute = ServicesEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCommercialRoute = ServicesCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/emergency': typeof ServicesEmergencyRoute
  '/services/ev-charger': typeof ServicesEvChargerRoute
  '/services/generator': typeof ServicesGeneratorRoute
  '/services/industrial': typeof ServicesIndustrialRoute
  '/services/panel-upgrades': typeof ServicesPanelUpgradesRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/security-systems': typeof ServicesSecuritySystemsRoute
  '/services/wiring-rewiring': typeof ServicesWiringRewiringRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/emergency': typeof ServicesEmergencyRoute
  '/services/ev-charger': typeof ServicesEvChargerRoute
  '/services/generator': typeof ServicesGeneratorRoute
  '/services/industrial': typeof ServicesIndustrialRoute
  '/services/panel-upgrades': typeof ServicesPanelUpgradesRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/security-systems': typeof ServicesSecuritySystemsRoute
  '/services/wiring-rewiring': typeof ServicesWiringRewiringRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/emergency': typeof ServicesEmergencyRoute
  '/services/ev-charger': typeof ServicesEvChargerRoute
  '/services/generator': typeof ServicesGeneratorRoute
  '/services/industrial': typeof ServicesIndustrialRoute
  '/services/panel-upgrades': typeof ServicesPanelUpgradesRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/security-systems': typeof ServicesSecuritySystemsRoute
  '/services/wiring-rewiring': typeof ServicesWiringRewiringRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/services/commercial'
    | '/services/emergency'
    | '/services/ev-charger'
    | '/services/generator'
    | '/services/industrial'
    | '/services/panel-upgrades'
    | '/services/residential'
    | '/services/security-systems'
    | '/services/wiring-rewiring'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/reviews'
    | '/sitemap.xml'
    | '/services/commercial'
    | '/services/emergency'
    | '/services/ev-charger'
    | '/services/generator'
    | '/services/industrial'
    | '/services/panel-upgrades'
    | '/services/residential'
    | '/services/security-systems'
    | '/services/wiring-rewiring'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/services/commercial'
    | '/services/emergency'
    | '/services/ev-charger'
    | '/services/generator'
    | '/services/industrial'
    | '/services/panel-upgrades'
    | '/services/residential'
    | '/services/security-systems'
    | '/services/wiring-rewiring'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/wiring-rewiring': {
      id: '/services/wiring-rewiring'
      path: '/wiring-rewiring'
      fullPath: '/services/wiring-rewiring'
      preLoaderRoute: typeof ServicesWiringRewiringRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/security-systems': {
      id: '/services/security-systems'
      path: '/security-systems'
      fullPath: '/services/security-systems'
      preLoaderRoute: typeof ServicesSecuritySystemsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/residential': {
      id: '/services/residential'
      path: '/residential'
      fullPath: '/services/residential'
      preLoaderRoute: typeof ServicesResidentialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/panel-upgrades': {
      id: '/services/panel-upgrades'
      path: '/panel-upgrades'
      fullPath: '/services/panel-upgrades'
      preLoaderRoute: typeof ServicesPanelUpgradesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/industrial': {
      id: '/services/industrial'
      path: '/industrial'
      fullPath: '/services/industrial'
      preLoaderRoute: typeof ServicesIndustrialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/generator': {
      id: '/services/generator'
      path: '/generator'
      fullPath: '/services/generator'
      preLoaderRoute: typeof ServicesGeneratorRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ev-charger': {
      id: '/services/ev-charger'
      path: '/ev-charger'
      fullPath: '/services/ev-charger'
      preLoaderRoute: typeof ServicesEvChargerRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/emergency': {
      id: '/services/emergency'
      path: '/emergency'
      fullPath: '/services/emergency'
      preLoaderRoute: typeof ServicesEmergencyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/commercial': {
      id: '/services/commercial'
      path: '/commercial'
      fullPath: '/services/commercial'
      preLoaderRoute: typeof ServicesCommercialRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCommercialRoute: typeof ServicesCommercialRoute
  ServicesEmergencyRoute: typeof ServicesEmergencyRoute
  ServicesEvChargerRoute: typeof ServicesEvChargerRoute
  ServicesGeneratorRoute: typeof ServicesGeneratorRoute
  ServicesIndustrialRoute: typeof ServicesIndustrialRoute
  ServicesPanelUpgradesRoute: typeof ServicesPanelUpgradesRoute
  ServicesResidentialRoute: typeof ServicesResidentialRoute
  ServicesSecuritySystemsRoute: typeof ServicesSecuritySystemsRoute
  ServicesWiringRewiringRoute: typeof ServicesWiringRewiringRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCommercialRoute: ServicesCommercialRoute,
  ServicesEmergencyRoute: ServicesEmergencyRoute,
  ServicesEvChargerRoute: ServicesEvChargerRoute,
  ServicesGeneratorRoute: ServicesGeneratorRoute,
  ServicesIndustrialRoute: ServicesIndustrialRoute,
  ServicesPanelUpgradesRoute: ServicesPanelUpgradesRoute,
  ServicesResidentialRoute: ServicesResidentialRoute,
  ServicesSecuritySystemsRoute: ServicesSecuritySystemsRoute,
  ServicesWiringRewiringRoute: ServicesWiringRewiringRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
